version: 0.2
phases:
  install:
    commands:
      # Install all dependencies
      - cd lambdas/add && npm install --production
      - cd lambdas/edit && npm install --production
      - cd lambdas/get && npm install --production
      - cd lambdas/task && npm install --production
  build:
    commands:
      # Use AWS SAM to package the application by using AWS CloudFormation
      - aws cloudformation package --template template.yml --s3-bucket $S3_BUCKET --output-template template-export.yml
artifacts:
  type: zip
  files:
    - template-export.yml